spring.application.name=cinema-xpress

#postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema-xpress
spring.datasource.username=postgres
spring.datasource.password=Aayush@54321

#cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

#redis
spring.data.redis.host=adoring-kettle-disciplined-94852.db.redis.io
spring.data.redis.port=12187
spring.data.redis.password=n1C9scwv8RJ0fcySLrYgmrnBBt8qIMh8
spring.data.redis.database=0